---
title: "EDA_project2_5"
author: "Li Ying"
date: "24 May 2015"
output: html_document
---

Load data 

```{r}
if(!exists("NEI")){
  NEI<-readRDS("./data/summarySCC_PM25.rds")
}
if(!exists("SCC")){
  SCC<-readRDS("./data/Source_Classification_Code.rds")
}
dir()

# merge the two data sets 
if(!exists("NEISCC")){
  NEISCC <- merge(NEI, SCC, by="SCC")
}

library(ggplot2)
```

How have emissions from motor vehicle sources changed from 1999–2008 in Baltimore City?
```{r}
# 24510 is Baltimore, see plot2.R
# Searching for ON-ROAD type in NEI
# Don't actually know it this is the intention, but searching for 'motor' in SCC only gave a subset (non-cars)
subsetNEI <- NEI[NEI$fips=="24510" & NEI$type=="ON-ROAD",  ]
aggregate <- aggregate(Emissions ~ year, subsetNEI, sum)

#plot
png("plot5.png", width=840, height=480)
g <- ggplot(aggregate, aes(factor(year), Emissions))
g <- g + geom_bar(stat="identity") +
  xlab("year") +
  ylab(expression('Total PM'[2.5]*" Emissions")) +
  ggtitle('Total Emissions from motor vehicle (type = ON-ROAD) in Baltimore City, Maryland (fips = "24510") from 1999 to 2008')
print(g)
dev.off()

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
