---
title: "EDA_Project2_3"
author: "Li Ying"
date: "24 May 2015"
output: html_document
---

Load data

```{r}
if(!exists("NEI")){
  NEI <- readRDS(".data/summarySCC_PM25.rds")
}
if(!exists("SCC")){
  SCC <- readRDS(".data/Source_Classification_Code.rds")
}
dir()
```

Of the four types of sources indicated by the type (point, nonpoint, onroad, nonroad) variable, which of these four sources have seen decreases in emissions from 1999–2008 for Baltimore City? Which have seen increases in emissions from 1999–2008? Use the ggplot2 plotting system to make a plot answer this question.

```{r}
library(ggplot2)

# 24510 is Baltimore, see plot2.R
Baltimore <- NEI[NEI$fips=="24510", ]
aggregate <- aggregate(Emissions~year+type,Baltimore,sum)

png("plot3.png", width=640, height=480)

g <- ggplot(aggregate, aes(year, Emissions, color = type))
g <- g + geom_line() +
  xlab("year") +
  ylab(expression('Total PM'[2.5]*" Emissions")) +
  ggtitle('Total Emissions in Baltimore City, Maryland (fips == "24510") from 1999 to 2008')
print(g)
dev.off()

```


